Repository MmgTools/mmg, pull requests merged in 2022-12, with the labels that each got.

#176 Feature/xreg
  cmake/testing/mmg2d_tests.cmake
  cmake/testing/mmg3d_tests.cmake
  cmake/testing/mmgs_tests.cmake
  doc/man/mmg2d.1.gz
  doc/man/mmg3d.1.gz
  doc/man/mmgs.1.gz
  src/common/analys.c
  src/common/boulep.c
  src/common/libmmgtypes.h
  src/common/libtools.c
  src/common/mmgcommon.h
  src/mmg2d/API_functions_2d.c
  src/mmg2d/analys_2d.c
  src/mmg2d/boulep_2d.c
  src/mmg2d/libmmg2d.h
  src/mmg2d/libmmg2d_private.h
  src/mmg2d/libmmg2d_tools.c
  src/mmg3d/API_functions_3d.c
  src/mmg3d/analys_3d.c
  src/mmg3d/libmmg3d.h
  src/mmg3d/libmmg3d_private.h
  src/mmg3d/libmmg3d_tools.c
  src/mmgs/API_functions_s.c
  src/mmgs/analys_s.c
  src/mmgs/libmmgs.h
  src/mmgs/libmmgs_private.h
  src/mmgs/libmmgs_tools.c
Labels: kind: enhancement, part: surface model, priority: high

#183 Cleaning of exec name generation and [skip output comparison] option in GitHub Action
  .github/workflows/main-job.yml
  cmake/modules/macros.cmake
  cmake/modules/mmg2d.cmake
  cmake/modules/mmg3d.cmake
  cmake/modules/mmgs.cmake
  cmake/testing/mmg3d_tests.cmake
  cmake/testing/mmg_tests.cmake
  cmake/testing/mmgs_tests.cmake
Labels: kind: enhancement, part: cmake, part: github action

#185 Feature/surfls
  cmake/testing/code/ridge-preservation-in-ls-mode.c
  cmake/testing/mmg2d_tests.cmake
  cmake/testing/mmg3d_tests.cmake
  cmake/testing/mmg_tests.cmake
  cmake/testing/mmgs_tests.cmake
  doc/man/mmg2d.1.gz
  doc/man/mmg3d.1.gz
  doc/man/mmgs.1.gz
  src/common/libmmgtypes.h
  src/common/libtools.c
  src/common/mmg2.c
  src/common/mmg2s.c
  src/common/mmgcommon.h
  src/common/mmgexterns.c
  src/common/mmgexterns.h
  src/common/scalem.c
  src/mmg2d/API_functions_2d.c
  src/mmg2d/analys_2d.c
  src/mmg2d/libmmg2d.c
  src/mmg2d/libmmg2d.h
  src/mmg2d/libmmg2d_private.h
  src/mmg2d/libmmg2d_tools.c
  src/mmg2d/mmg2d.c
  src/mmg2d/mmg2d6.c
  src/mmg3d/API_functions_3d.c
  src/mmg3d/analys_3d.c
  src/mmg3d/libmmg3d.c
  src/mmg3d/libmmg3d.h
  src/mmg3d/libmmg3d_private.h
  src/mmg3d/libmmg3d_tools.c
  src/mmg3d/mmg3d.c
  src/mmg3d/mmg3d1_delone.c
  src/mmg3d/mmg3d2.c
  src/mmg3d/mmg3d2s.c
  src/mmg3d/mmg3dexterns.h
  src/mmgs/API_functions_s.c
  src/mmgs/libmmgs.c
  src/mmgs/libmmgs.h
  src/mmgs/libmmgs_tools.c
  src/mmgs/mmgs.c
  src/mmgs/mmgs2.c
Labels: part: ls discretization, priority: high

#188 Feature/ls bijective map
  src/common/mmg2.c
Labels: kind: enhancement, part: ls discretization, priority: high

#189 Feature/avoid surface pinching
  src/mmg3d/colver_3d.c
  src/mmg3d/swap_3d.c
Labels: kind: bug, part: mesh adaptation, priority: high
