Repository MmgTools/mmg, pull requests merged in 2023-03, with the labels that each got.

#205 Non manifold surface does not lead to an error anymore : warning instead
  src/mmg3d/mmg3d1_delone.c
  src/mmg3d/mmg3d1_pattern.c
Labels: kind: enhancement, part: ls discretization

#206 Feature/input param file
  .vscode/c_cpp_properties.json
  cmake/testing/mmg2d_tests.cmake
  cmake/testing/mmg3d_tests.cmake
  cmake/testing/mmgs_tests.cmake
  src/common/API_functions.c
  src/common/libmmgcommon_private.h
  src/common/libmmgtypes.h
  src/common/libtools.c
  src/mmg2d/API_functions_2d.c
  src/mmg2d/API_functionsf_2d.c
  src/mmg2d/libmmg2d.h
  src/mmg2d/libmmg2d_tools.c
  src/mmg3d/API_functions_3d.c
  src/mmg3d/API_functionsf_3d.c
  src/mmg3d/libmmg3d.h
  src/mmg3d/libmmg3d_tools.c
  src/mmgs/API_functions_s.c
  src/mmgs/API_functionsf_s.c
  src/mmgs/libmmgs.h
  src/mmgs/libmmgs_tools.c
  src/mmgs/mmgs.c
Labels: kind: enhancement, part: application, part: I/O

#207 Feature/xreg2
  cmake/testing/mmg2d_tests.cmake
  cmake/testing/mmg_tests.cmake
  src/common/API_functions.c
  src/common/libmmgtypes.h
  src/common/libtools.c
  src/common/mmgcommon_private.h
  src/mmg2d/API_functions_2d.c
  src/mmg2d/analys_2d.c
  src/mmg2d/libmmg2d.h
  src/mmg2d/libmmg2d_tools.c
  src/mmg3d/API_functions_3d.c
  src/mmg3d/analys_3d.c
  src/mmg3d/libmmg3d.h
  src/mmg3d/libmmg3d_tools.c
  src/mmgs/API_functions_s.c
  src/mmgs/analys_s.c
  src/mmgs/libmmgs.h
  src/mmgs/libmmgs_tools.c
Labels: kind: enhancement
