Repository MmgTools/mmg, pull requests merged in 2024-03, with the labels that each got.

#246 Modified max numbers of entities
  src/mmg2d/zaldy_2d.c
  src/mmg3d/zaldy_3d.c
  src/mmgs/zaldy_s.c
Labels: kind: bug, part: int64

#250 Fixes in the API documentation
  src/mmg3d/API_functions_3d.c
  src/mmg3d/libmmg3d.h
Labels: kind: enhancement, part: mmg3d, part: documentation

#251 Develop
  src/mmg2d/libmmg2d.h
  src/mmg3d/libmmg3d.h
  src/mmgs/libmmgs.h
Labels: kind: enhancement, part: documentation

#252 Develop
  src/mmg2d/libmmg2d.h
  src/mmg3d/libmmg3d.h
Labels: kind: enhancement, part: mmg2d, part: documentation

#253 API Documentation fixes mainly in libmmgs.h, and a workaround for a Doxygen problem
  src/common/inout.c
  src/mmg2d/libmmg2d.h
  src/mmg3d/libmmg3d.h
  src/mmgs/libmmgs.h
Labels: kind: enhancement, part: documentation

#247 Modification of integer initialization to INT/LONG_MAX
  CMakeLists.txt
  src/common/mmg2.c
  src/common/mmgcmakedefines.h.in
  src/mmg2d/API_functions_2d.c
  src/mmg2d/hash_2d.c
  src/mmg3d/API_functions_3d.c
  src/mmg3d/hash_3d.c
  src/mmgs/API_functions_s.c
Labels: kind: enhancement, part: int64

#255 Fixed minor warning related to integer types
  src/mmg3d/mmg3d3.c
Labels: kind: enhancement, part: compilation

#244 64-bit integers and CI tests
  .github/workflows/main-job.yml
  cmake/testing/libmmg3d_tests.cmake
  cmake/testing/mmg2d_tests.cmake
  cmake/testing/mmg3d_tests.cmake
  src/mmg2d/inout_2d.c
  src/mmg2d/velextls_2d.c
  src/mmg3d/inout_3d.c
  src/mmg3d/velextls_3d.c
  src/mmgs/inout_s.c
Labels: kind: bug, kind: enhancement, part: I/O, part: int64

#241 Update edge tags in splits
  src/mmg3d/split_3d.c
Labels: kind: enhancement, part: surface model

#256 various bits of documentation
  src/common/libmmgtypes.h
  src/mmg2d/libmmg2d.h
  src/mmg3d/boulep_3d.c
  src/mmg3d/libmmg3d.h
  src/mmg3d/mmg3d2.c
  src/mmgs/libmmgs.h
Labels: kind: enhancement, part: documentation
